travis:
  secure:
    BINSTAR_TOKEN: MixRDlNk0+fBrayQ1Sy548Ww1V4Isy2oxMPvMtD8aTE5nEcelRh1Tw5j0pMsJJos3JZ+jZjJ1R+OocW5DLHm+N75EuD2VlrzM4IXT5twMc6jnAlSiyQ8tfwAr40K3QBfzItj7GkHaXtLqNdarjMrZTxtpmZngWF5UONbUXY4gpPoKSlNGWbLwtmSjDs6cGQynm1T169vVwCMnWSztUX27Go/HPWJmW7Vf2KNg25dxdX9NT13ccNC8MND9Oj77PM0Mgj6Ovj9u3mUD/4wJRADFYg3obQugKDJuHQ87ghOHREM+cnmByNzUDW713aag6jc4V28NmtKBrELbrE67SwZZx7j64ixwH5alsLrI6Un4DLRdWGA2aeOZtCOO7lpoUI49V1pw3VQkqbKurefASz5S/we240/fga6QhchnRKqheatSSAmvXOFNsLW3cqMQQueWFWpUIwzsuedsoe7fJYRlmJRLrV/+9XMtHFNGJAGLrINeI5l52ylZbJ/M6ZAs/WOwAyRRy1967MVYC7Fktud4jijn+VyIAJvzhMKgrvdfVIVIf43/3Me3WMhXNky9P4JIzAl47J70GLhc4xcylS+UZZ6KYoF3kHqGln6duQKegcDtioXI0aW7VH649WGg5oFAfjny18+Eht/YehJ5C2LEhkQr45WVC55BLiC/XPDWsc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
