travis:
  secure:
    BINSTAR_TOKEN: L1ry9YgBmfGOMIXFy7fDQuf3+bL1XFUa/kCHB6zyxMKmqRsTP6QsGWZY7l40VuvISNeDE1GWsma5vATr7zk9Oi1tcEYvb5smeOgiFcFJQTRQDrYydt+HiATx/MRkLZOHNca71wUfG9msSp8Mdyp0zqrpi3HdsFg+t91sLFUHN0Wx1bMhTm8ruhJ4ugI5zK/EKG3nm0Fc6ApJQ4LC5dd8SJgoSubOIen1rvOgjbA3wdotTLr2wxBe5mJqYNkn1C4mZv8ICmRiGyd3en4afx+tajNkf2Bx3r+XtIBRopMn/KZe/q2FvHb+lJeKlaJDt0MiBGG9lDvm58VB1l+im/P/bnSXm0G+0PuB0XGfisZTTPJ646XEkek9G148YIesZU9nz7ZNGqv4f0vgJMRMyCslcdCrcbbzK+nl96LyzKrW2jSQQ3Ovsa1O4wLEobt99xcxXoQkcDvS5c0Zc3nDCDOlZsiNykYrECxcrESVFwLkwG1mc2vs2OQoIAa6G9/BJThdH2aJINoS+oD4DC680Qnlysjbx2k/ajfgp4qRXnuYds8qmexb2K8srVrvJkmZWy7qBbvdILwfIPl++Yr6+QY6ku36WCfTHSEJebAuiWnHCkwEASRY9jUmMmXHXFJC9rne99CimVUiYol3+rvS3RvnY6YEWEInzbkQD1S/MM/s5IA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
